"""empty message

Revision ID: 2416f2b161f7
Revises: 
Create Date: 2021-07-24 19:38:18.294818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2416f2b161f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primerNombre', sa.String(length=255), nullable=False),
    sa.Column('segundoNombre', sa.String(length=255), nullable=True),
    sa.Column('apellidoPaterno', sa.String(length=255), nullable=False),
    sa.Column('apellidoMaterno', sa.String(length=255), nullable=True),
    sa.Column('fono', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EstadoReserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primerNombre', sa.String(length=255), nullable=False),
    sa.Column('segundoNombre', sa.String(length=255), nullable=True),
    sa.Column('apellidoPaterno', sa.String(length=255), nullable=False),
    sa.Column('apellidoMaterno', sa.String(length=255), nullable=True),
    sa.Column('fono', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechaReserva', sa.Date(), nullable=False),
    sa.Column('horaReserva', sa.Time(), nullable=False),
    sa.Column('servicioID', sa.Integer(), nullable=False),
    sa.Column('clienteID', sa.Integer(), nullable=False),
    sa.Column('estadoReservaID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clienteID'], ['Clientes.id'], ),
    sa.ForeignKeyConstraint(['estadoReservaID'], ['EstadoReserva.id'], ),
    sa.ForeignKeyConstraint(['servicioID'], ['Servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsuarioServicios',
    sa.Column('usuarioID', sa.Integer(), nullable=False),
    sa.Column('servicioID', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicioID'], ['Servicios.id'], ),
    sa.ForeignKeyConstraint(['usuarioID'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuarioID', 'servicioID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsuarioServicios')
    op.drop_table('Reserva')
    op.drop_table('Usuarios')
    op.drop_table('Servicios')
    op.drop_table('EstadoReserva')
    op.drop_table('Clientes')
    # ### end Alembic commands ###
